title: Simple Page
icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

tabs:
  intro:
    label: Intro
    icon: text
    columns:
      - width: 2/3
        fields:
          headline:
            label: Headline
            type: text
            required: true
          subHeadline:
            label: Headline
            type: text
          previewText:
            label: Previewtext Text
            type: textarea
            required: true
          text:
            label: Text
            type: textarea
            size: medium
            required: true

      - width: 1/3
        sections:
          headerImage:
            type: files
            max: 5
            accept: image


  content:
    label: Content
    icon: text
    fields:
      mybuilder:
        label: Paragraphs
        type: builder
        fieldsets:
          paragraph:
            name: Paragraph
            fields:
              paragraphHeadline:
                label: Headline
                type: text
              paragraphText:
                label: Text
                type: textarea

          imagePragraph:
            name: Paragraph with Images
            fields:
              paragraphMultiHeadline:
                label: Headline
                type: text
              mybuilder:
                label: Paragraphs
                type: builder
                fieldsets:
                  bodyMultiText:
                    name: Paragraph
                    fields:
                      paragraphMultiText:
                        label: Text
                        type: textarea
                  bodyMultiImage:
                    name: Image
                    fields:
                      paragraphMultiImage:
                        label: Image
                        type: files










                        #asdf
