title: Site

columns:
  - width: 1/2
    sections:
      pages:
        type: pages
        create: 
          - default
          - paragraph
        template:
          - home
          - default
          - paragraph