title: Site

columns:
  - width: 1/1
    sections:
      main:
        type: pages
        template:
          - home
  - width: 1/2
    sections:

      drafts:
        headline: Drafts
        type: pages
        status: drafts
        create:
          - default
        template:
          - default
          - news
          - research

      published:
        headline: Main Navigation
        type: pages
        status: listed
        create:
          - default
        template:
          - default
          - news
          - research

      invisible:
        headline: Invisible Pages
        type: pages
        status: unlisted
        create:
          - default
        template:
          - default
          - news
          - research


  - width: 1/2
      fields:
        header:
          label: Header Meta Navigation
          type: pages
          template:
            - default
        footer:
          label: Footer Meta Navigation
          type: pages
          template:
            - default
